stages:
  - build
  - deploy

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH
  DOCKER_REGISTRY: registry.digitalocean.com
  IMAGE_NAME: 'everclub/front'
  APP_NAME: 'front'
  HELM_CHART: 'front'
  KUB_NAMESPACE: 'everclub-bsc'
  TAG_COMMIT: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

build:
  stage: build
  tags:
    - deploy
  before_script:
    - pwd
    - echo $CI_COMMIT_REF_NAME
    - doctl auth init
    - doctl registry login
  script:
    - docker build --build-arg API_URL=$ENV_API_URL --build-arg CHAIN_ID=$BLOCKCHAIN_ID -t $DOCKER_REGISTRY/$IMAGE_NAME:$TAG_COMMIT .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$TAG_COMMIT
    - docker rmi --force $DOCKER_REGISTRY/$IMAGE_NAME:$TAG_COMMIT
    - docker rmi $(docker images -f "dangling=true" -q) --force
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - develop
    - main

deploy:
  stage: deploy
  tags:
    - deploy
  before_script:
    - doctl kubernetes cluster kubeconfig save $KUBERNETES_CLUSTER
  script:
    - helm upgrade --install --wait --atomic --debug --timeout 300s
      $APP_NAME ./helm/$HELM_CHART -n $KUB_NAMESPACE
      --values ./helm/env/$FILENAME_ENV.yaml
      --set image.tag=$TAG_COMMIT --set image.repository=$IMAGE_NAME
    - doctl auth remove --context default
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - develop
    - main
